language: python
dist: xenial
sudo: true

python:
  - 3.7

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALEVNS=1

install:
  - pip install pipenv
  - pipenv sinc -d

script:
  - pipenv run flake8 .