# Generated by Django 2.2.4 on 2019-09-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user         '
                          'can log into this admin site.',
                verbose_name='staff status'),
        ),
    ]
